### ISSUE TITLE
TLS cert not checked?

### ISSUE THREAD

**Issue by octomike** [spm/spm-docker#3]
wget is passed the parameter `--no-check-certificates` although TLS settings of https://www.fil.ion.ucl.ac.uk seem to be fine.

**Comment by gllmflndn** [comment]
Thanks @octomike. This was added in 643478d  after noticing that the certificate check was not working with `wget` once `LD_LIBRARY_PATH` was edited to use the libraries shipped with MATLAB before the system ones. I would hope this flag to be removed at some point but I'm not sure it is possible yet with R2018b used here so far.

**Comment by octomike** [comment]
It does work with `LD_LIBRARY_PATH` pointing to R2018b - should I open a PR for this?

I am also in favor of using `--progress=bar:force` as this does not clutter the build output. What do you think?

**Comment by gllmflndn** [comment]
If it works then I'm happy with it. Please open a PR containing both suggestions. Thanks!
